Config = {}
Config.Locale = 'ru'

Config.Zones = {
	{
		Categories = { ['Химия'] = 4, ['Медицина'] = 2 },
		Identifier = 'lab_forge',
		Title = 'Лаборатория',
		Position = { x = -449.15, y = -307.87, z = 34.6 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда'] = 4, ['Напитки'] = 2, ['Оружейники'] = 2, ['Нефтяники'] = 2, ['Приборостроение'] = 2, ['Химия'] = 2, ['Металлургия'] = 2, ['Фермерство'] = 2, ['Медицина'] = 2, },
		Identifier = 'master_forge',
		Title = 'Тестовая',
		Position = { x = 411.2, y = -975.8, z = 29.4 },
		DrawDistance = 20,
	},
    -- Ballas
    {
		Categories = { ['Химия'] = 2, },
		Identifier = 'lab_ballas',
		Title = 'Лаборатория',
		Position = { x = 90.32, y = -1986.81, z = 20.42 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Оружейники'] = 2, },
		Identifier = 'gun_ballas',
		Title = 'Оружейная',
		Position = { x = 108.46, y = -1981.02, z = 20.96 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда'] = 4, ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_ballas',
		Title = 'Кухня',
		Position = { x = 114.11, y = -1970.85, z = 21.33 },
		DrawDistance = 1,
	},
    -- Families
    {
		Categories = { ['Химия'] = 2, },
		Identifier = 'lab_fam',
		Title = 'Лаборатория',
		Position = { x = -136.42, y = -1611.67, z = 35.03 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Оружейники'] = 2, },
		Identifier = 'gun_fam',
		Title = 'Оружейная',
		Position = { x = -135.36, y = -1609.05, z = 35.03 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда'] = 4, ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_fam',
		Title = 'Кухня',
		Position = { x = -150.64, y = -1605.77, z = 35.03 },
		DrawDistance = 1,
	},
    -- Vagos
    {
		Categories = { ['Химия'] = 2, },
		Identifier = 'lab_vag',
		Title = 'Лаборатория',
		Position = { x = 335.84, y = -2019.19, z = 22.39 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Оружейники'] = 2, },
		Identifier = 'gun_vag',
		Title = 'Оружейная',
		Position = { x = 331.18, y = -2012.91, z = 22.39 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда'] = 4, ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_vag',
		Title = 'Кухня',
		Position = { x = 347.87, y = -2030.09, z = 22.39 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда'] = 4, },
		Identifier = 'tinker_vag',
		Title = 'Верстак',
		Position = { x = 365.56, y = -2040.94, z = 22.39 },
		DrawDistance = 1,
	},
    -- Marabunta
    {
		Categories = { ['Химия'] = 2, },
		Identifier = 'lab_mar',
		Title = 'Лаборатория',
		Position = { x = 1435.42, y = -1488.55, z = 66.62 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Оружейники'] = 2, },
		Identifier = 'gun_mar',
		Title = 'Оружейная',
		Position = { x = 1439.48, y = -1490.9, z = 66.62 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда'] = 4, ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_mar',
		Title = 'Кухня',
		Position = { x = 1437.64, y = -1481.33, z = 63.7 },
		DrawDistance = 1,
	},
    -- Bean Machine
    {
		Categories = { ['Еда'] = 40, ['Еда: домашняя'] = 40, ['Еда: суши'] = 40, ['Еда: рестораны'] = 40, ['Еда: cладости'] = 100, ['Напитки'] = 40 },
		Identifier = 'kitchen_bm',
		Title = 'Кухня',
		Position = { x = -825.98, y = -599.43, z = 29.03 },
		DrawDistance = 1,
	},
    -- Human Labs
    {
		Categories = { ['Химия'] = 2, },
		Identifier = 'lab_hm',
		Title = 'Лаборатория',
		Position = { x = 3559.86, y = 3673.69, z = 28.12 },
		DrawDistance = 1.5,
	},
    -- Zonah
    {
		Categories = { ['Еда'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_zh',
		Title = 'Кухня',
		Position = { x = -437.0, y = -341.15, z = 34.6 },
		DrawDistance = 1,
	},
    -- BurgerShot
    {
		Categories = { ['Еда'] = 4, ['Еда: фастфуд'] = 40, },
		Identifier = 'kitchen_bs',
		Title = 'Кухня',
		Position = { x = -1199.11, y = -901.07, z = 14.0 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Напитки'] = 2 },
		Identifier = 'kitchen_bs2',
		Title = 'Кухня',
		Position = { x = -1197.54, y = -897.62, z = 14.0 },
		DrawDistance = 1,
	},
    --=================[МОТЕЛИ]=================
    --АЛЬТА СТРИТ
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast1',
		Title = 'Кухня',
		Position = { x = 311.87, y = -222.11, z = 54.23 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast2',
		Title = 'Кухня',
		Position = { x = 303.76, y = -213.46, z = 54.23 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast3',
		Title = 'Кухня',
		Position = { x = 307.63, y = -203.26, z = 54.23 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast4',
		Title = 'Кухня',
		Position = { x = 316.59, y = -191.44, z = 54.23 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast5',
		Title = 'Кухня',
		Position = { x = 311.87, y = -222.11, z = 58.02 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast6',
		Title = 'Кухня',
		Position = { x = 303.76, y = -213.46, z = 58.02 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast7',
		Title = 'Кухня',
		Position = { x = 307.63, y = -203.26, z = 58.02 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast8',
		Title = 'Кухня',
		Position = { x = 316.59, y = -191.44, z = 58.02 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast9',
		Title = 'Кухня',
		Position = { x = 335.58, y = -231.3, z = 54.23 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast10',
		Title = 'Кухня',
		Position = { x = 342.43, y = -220.03, z = 54.23 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast11',
		Title = 'Кухня',
		Position = { x = 346.35, y = -209.86, z = 54.23 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast12',
		Title = 'Кухня',
		Position = { x = 350.23, y = -199.58, z = 54.23 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast13',
		Title = 'Кухня',
		Position = { x = 335.58, y = -231.3, z = 58.02 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast14',
		Title = 'Кухня',
		Position = { x = 342.43, y = -220.03, z = 58.02 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast15',
		Title = 'Кухня',
		Position = { x = 346.35, y = -209.86, z = 58.02 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_altast16',
		Title = 'Кухня',
		Position = { x = 350.23, y = -199.58, z = 58.02 },
		DrawDistance = 1,
	},
    --ЭЛЬ РАНЧО
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_ranchost1',
		Title = 'Кухня',
		Position = { x = 546.41, y = -1771.26, z = 29.29 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_ranchost2',
		Title = 'Кухня',
		Position = { x = 549.57, y = -1764.73, z = 29.29 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_ranchost3',
		Title = 'Кухня',
		Position = { x = 552.74, y = -1758.08, z = 29.29 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_ranchost4',
		Title = 'Кухня',
		Position = { x = 555.77, y = -1751.5, z = 29.29 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_ranchost5',
		Title = 'Кухня',
		Position = { x = 558.7, y = -1744.82, z = 29.29 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_ranchost6',
		Title = 'Кухня',
		Position = { x = 552.17, y = -1780.04, z = 33.44 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_ranchost7',
		Title = 'Кухня',
		Position = { x = 545.56, y = -1776.88, z = 33.44 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_ranchost8',
		Title = 'Кухня',
		Position = { x = 547.43, y = -1763.66, z = 33.44 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_ranchost9',
		Title = 'Кухня',
		Position = { x = 550.58, y = -1757.09, z = 33.44 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_ranchost10',
		Title = 'Кухня',
		Position = { x = 553.5, y = -1750.38, z = 33.44 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_ranchost11',
		Title = 'Кухня',
		Position = { x = 556.64, y = -1743.9, z = 33.44 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_ranchost12',
		Title = 'Кухня',
		Position = { x = 568.76, y = -1744.41, z = 33.44 },
		DrawDistance = 1,
	},
    -- КЛИНТОН АВЕНЮ
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton1',
		Title = 'Кухня',
		Position = { x = 486.55, y = 193.65, z = 104.74 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton2',
		Title = 'Кухня',
		Position = { x = 475.17, y = 208.21, z = 104.74 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton3',
		Title = 'Кухня',
		Position = { x = 480.48, y = 222.86, z = 104.74 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton4',
		Title = 'Кухня',
		Position = { x = 484.74, y = 234.33, z = 104.74 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton5',
		Title = 'Кухня',
		Position = { x = 504.7, y = 242.17, z = 104.74 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton6',
		Title = 'Кухня',
		Position = { x = 523.39, y = 235.28, z = 104.74 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton7',
		Title = 'Кухня',
		Position = { x = 536.2, y = 214.28, z = 104.74 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton8',
		Title = 'Кухня',
		Position = { x = 529.9, y = 196.9, z = 104.74 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton9',
		Title = 'Кухня',
		Position = { x = 510.92, y = 184.81, z = 104.74 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton10',
		Title = 'Кухня',
		Position = { x = 486.55, y = 193.65, z = 108.31 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton11',
		Title = 'Кухня',
		Position = { x = 475.17, y = 208.21, z = 108.31 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton12',
		Title = 'Кухня',
		Position = { x = 480.48, y = 222.86, z = 108.31 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton13',
		Title = 'Кухня',
		Position = { x = 484.74, y = 234.33, z = 108.31 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton14',
		Title = 'Кухня',
		Position = { x = 499.75, y = 243.92, z = 108.31 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton15',
		Title = 'Кухня',
		Position = { x = 511.41, y = 239.65, z = 108.31 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton16',
		Title = 'Кухня',
		Position = { x = 523.6, y = 235.23, z = 108.31 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton17',
		Title = 'Кухня',
		Position = { x = 538.38, y = 220.25, z = 108.31 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton18',
		Title = 'Кухня',
		Position = { x = 534.08, y = 208.41, z = 108.31 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton19',
		Title = 'Кухня',
		Position = { x = 529.72, y = 196.49, z = 108.31 },
		DrawDistance = 1,
	},
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_klinton20',
		Title = 'Кухня',
		Position = { x = 511.04, y = 184.82, z = 108.31 },
		DrawDistance = 1,
	},
    -- Bennys
    {
		Categories = { ['Еда: домашняя'] = 4, ['Напитки'] = 2 },
		Identifier = 'kitchen_benny',
		Title = 'Кухня',
		Position = { x = -205.53, y = -1339.74, z = 30.91 },
		DrawDistance = 1,
	},



}
