
RegisterNetEvent('drugs:coke')
AddEventHandler('drugs:coke', function()
  local playerPed = PlayerPedId()

    RequestAnimSet("MOVE_M@QUICK")
    while not HasAnimSetLoaded("MOVE_M@QUICK") do
      Citizen.Wait(0)
    end
    TriggerEvent('dpemotes:emote', 'uncuff')
    Citizen.Wait(3000)
    ClearPedTasks(playerPed)
    SetTimecycleModifier("spectator5")
    SetPedMotionBlur(playerPed, true)
    SetPedMovementClipset(playerPed, "MOVE_M@QUICK", true)
    SetPedIsDrunk(playerPed, true)
	SetPedMoveRateOverride(PlayerId(),10.0)
    SetRunSprintMultiplierForPlayer(PlayerId(),1.49)
    AnimpostfxPlay("DrugsMichaelAliensFight", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 3.0)
    TriggerServerEvent("stress:remove", 70000)
    Citizen.Wait(50000)
    SetPedMoveRateOverride(PlayerId(),1.0)
    SetRunSprintMultiplierForPlayer(PlayerId(),1.0)
    Citizen.Wait(150000)
    SetPedIsDrunk(GetPlayerPed(-1), false)
    SetPedMotionBlur(playerPed, false)
    ResetPedMovementClipset(GetPlayerPed(-1))
    AnimpostfxStopAll()
    ShakeGameplayCam("DRUNK_SHAKE", 0.0)
    SetTimecycleModifierStrength(0.0)
end)

RegisterNetEvent('drugs:weed')
AddEventHandler('drugs:weed', function()
  local playerPed = PlayerPedId()

    RequestAnimSet("move_m@drunk@a")
    while not HasAnimSetLoaded("move_m@drunk@a") do
      Citizen.Wait(0)
    end
    TriggerEvent('dpemotes:emote', 'uncuff')
    Citizen.Wait(3000)
    ClearPedTasks(playerPed)
    SetTimecycleModifier("spectator6")
    SetPedMotionBlur(playerPed, true)
    SetPedMovementClipset(playerPed, "move_m@drunk@a", true)
    SetPedIsDrunk(playerPed, true)
    AnimpostfxPlay("MenuMGTournamentIn", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 1.0)
    TriggerServerEvent("stress:remove", 70000)
    Citizen.Wait(150000)
    SetPedMoveRateOverride(PlayerId(),1.0)
    SetRunSprintMultiplierForPlayer(PlayerId(),1.0)
    SetPedIsDrunk(GetPlayerPed(-1), false)
    SetPedMotionBlur(playerPed, false)
    ResetPedMovementClipset(GetPlayerPed(-1))
    AnimpostfxStopAll()
    ShakeGameplayCam("DRUNK_SHAKE", 0.0)
    SetTimecycleModifierStrength(0.0)
end)

RegisterNetEvent('drugs:lsd')
AddEventHandler('drugs:lsd', function()
  local playerPed = PlayerPedId()

    RequestAnimSet("move_m@hobo@a")
    while not HasAnimSetLoaded("move_m@hobo@a") do
      Citizen.Wait(0)
    end
    TriggerEvent('dpemotes:emote', 'uncuff')
    Citizen.Wait(3000)
    ClearPedTasks(playerPed)
    SetPedMotionBlur(playerPed, true)
    SetPedMovementClipset(playerPed, "move_m@hobo@a", true)
    SetPedIsDrunk(playerPed, true)
    SetTimecycleModifier("DRUG_gas_huffin")
    SetTimecycleModifierStrength(0.90)
    AnimpostfxPlay("MenuMGSelectionIn", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 2.0)
    Citizen.Wait(10000)
    SetTimecycleModifierStrength(1.5)
    ShakeGameplayCam("SKY_DIVING_SHAKE", 3.5)
    AnimpostfxPlay("DrugsTrevorClownsFightIn", 10000001, true)
    Citizen.Wait(7000)
    AnimpostfxStopAll()
    -- PlaySound(-1, "Frontend_Beast_Frozen_Screen_Loop", "FM_Events_Sasquatch_Sounds", 0, 0, 0)
    SetTimecycleModifierStrength(10.0)
    AnimpostfxPlay("MP_Celeb_Lose_Out", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 5.5)
    Citizen.Wait(7000)
    SetTimecycleModifierStrength(5.0)
    Citizen.Wait(7000)
    ShakeGameplayCam("DEATH_FAIL_IN_EFFECT_SHAKE", 3.5)
    AnimpostfxStopAll()
    SetTimecycleModifierStrength(3.5)
    ShakeGameplayCam("DEATH_FAIL_IN_EFFECT_SHAKE", 3.5)
    -- AnimpostfxPlay("MP_corona_switch", 10000001, true)
    Citizen.Wait(7000)
    SetTimecycleModifierStrength(10.0)
    ShakeGameplayCam("SKY_DIVING_SHAKE", 3.5)
    Citizen.Wait(10000)
    AnimpostfxStopAll()
    SetTimecycleModifier("DRUG_gas_huffin")
    SetTimecycleModifierStrength(0.90)
    -- AnimpostfxPlay("MenuMGSelectionIn", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 5.0)
    Citizen.Wait(10000)
    SetTimecycleModifierStrength(1.5)
    ShakeGameplayCam("SKY_DIVING_SHAKE", 5.5)
    -- AnimpostfxPlay("DrugsTrevorClownsFightIn", 10000001, true)
    -- StopSound(-1, "Frontend_Beast_Frozen_Screen_Loop", "FM_Events_Sasquatch_Sounds", 0, 0, 0)
    Citizen.Wait(7000)
    SetTimecycleModifierStrength(10.0)
    AnimpostfxPlay("MP_Celeb_Lose_Out", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 5.5)
    Citizen.Wait(7000)
    SetTimecycleModifierStrength(5.0)
    Citizen.Wait(7000)
    ShakeGameplayCam("DEATH_FAIL_IN_EFFECT_SHAKE", 3.5)
    AnimpostfxStopAll()
    SetTimecycleModifierStrength(3.5)
    ShakeGameplayCam("DEATH_FAIL_IN_EFFECT_SHAKE", 3.5)
    AnimpostfxPlay("MP_corona_switch", 10000001, true)
    Citizen.Wait(7000)
    SetTimecycleModifierStrength(10.0)
    ShakeGameplayCam("SKY_DIVING_SHAKE", 3.5)
    Citizen.Wait(10000)
    AnimpostfxStopAll()
    SetTimecycleModifier("DRUG_gas_huffin")
    SetTimecycleModifierStrength(0.90)
    AnimpostfxPlay("MenuMGSelectionIn", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 5.0)
    Citizen.Wait(10000)
    SetTimecycleModifierStrength(1.5)
    ShakeGameplayCam("SKY_DIVING_SHAKE", 5.5)
    AnimpostfxPlay("DrugsTrevorClownsFightIn", 10000001, true)
    Citizen.Wait(7000)
    AnimpostfxStopAll()
    SetTimecycleModifier("DRUG_gas_huffin")
    SetTimecycleModifierStrength(0.90)
    AnimpostfxPlay("MenuMGSelectionIn", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 2.0)
    Citizen.Wait(20000)
    SetPedMotionBlur(playerPed, true)
    SetPedMovementClipset(playerPed, "move_m@hobo@a", true)
    SetPedIsDrunk(playerPed, true)
    SetTimecycleModifier("DRUG_gas_huffin")
    SetTimecycleModifierStrength(0.90)
    AnimpostfxPlay("MenuMGSelectionIn", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 2.0)
    Citizen.Wait(100000)
    SetPedMoveRateOverride(PlayerId(),1.0)
    SetRunSprintMultiplierForPlayer(PlayerId(),1.0)
    SetPedIsDrunk(GetPlayerPed(-1), false)
    SetPedMotionBlur(playerPed, false)
    ResetPedMovementClipset(GetPlayerPed(-1))
    AnimpostfxStopAll()
    ShakeGameplayCam("DRUNK_SHAKE", 0.0)
    SetTimecycleModifierStrength(0.0)
end)

RegisterNetEvent('drugs:meth')
AddEventHandler('drugs:meth', function()
  local playerPed = PlayerPedId()

    RequestAnimSet("move_m@drunk@moderatedrunk")
    while not HasAnimSetLoaded("move_m@drunk@moderatedrunk") do
      Citizen.Wait(0)
    end
    TriggerEvent('dpemotes:emote', 'uncuff')
    Citizen.Wait(3000)
    ClearPedTasks(playerPed)
    SetPedMotionBlur(playerPed, true)
    SetPedMovementClipset(playerPed, "move_m@drunk@moderatedrunk", true)
    SetPedIsDrunk(playerPed, true)
    SetTimecycleModifier("spectator5")
    AnimpostfxPlay("SuccessMichael", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 1.5)
    TriggerServerEvent("stress:remove", 70000)
    Citizen.Wait(150000)
    SetPedMoveRateOverride(PlayerId(),1.0)
    SetRunSprintMultiplierForPlayer(PlayerId(),1.0)
    SetPedIsDrunk(GetPlayerPed(-1), false)
    SetPedMotionBlur(playerPed, false)
    ResetPedMovementClipset(GetPlayerPed(-1))
    AnimpostfxStopAll()
    ShakeGameplayCam("DRUNK_SHAKE", 0.0)
    SetTimecycleModifierStrength(0.0)
end)

RegisterNetEvent('drugs:stimulator')
AddEventHandler('drugs:stimulator', function()
  local playerPed = PlayerPedId()

    RequestAnimSet("move_action@generic@core")
    while not HasAnimSetLoaded("move_action@generic@core") do
      Citizen.Wait(0)
    end
    TriggerEvent('dpemotes:emote', 'uncuff')
    Citizen.Wait(3000)
    ClearPedTasks(playerPed)
    SetPedMotionBlur(playerPed, true)
    SetPedMovementClipset(playerPed, "move_action@generic@core", true)
    SetPedIsDrunk(playerPed, true)
    SetTimecycleModifier("damage")
    SetTimecycleModifierStrength(1.5)
    AnimpostfxPlay("RaceTurbo", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 1.5)
    SetEntityHealth(GetPlayerPed(-1), 200)
    SetPedArmour(PlayerPedId(), 100)
    TriggerServerEvent("stress:add", 100000)
    Citizen.Wait(150000)
    SetPedMoveRateOverride(PlayerId(),1.0)
    SetRunSprintMultiplierForPlayer(PlayerId(),1.0)
    SetPedIsDrunk(GetPlayerPed(-1), false)
    SetPedMotionBlur(playerPed, false)
    ResetPedMovementClipset(GetPlayerPed(-1))
    AnimpostfxStopAll()
    ShakeGameplayCam("DRUNK_SHAKE", 0.0)
    SetTimecycleModifierStrength(0.0)
    SetPedArmour(PlayerPedId(), 0)
    SetEntityHealth(GetPlayerPed(-1), 120)
end)

RegisterNetEvent('drugs:morphine')
AddEventHandler('drugs:morphine', function()
  local playerPed = PlayerPedId()

    RequestAnimSet("move_m@hobo@a")
    while not HasAnimSetLoaded("move_m@hobo@a") do
      Citizen.Wait(0)
    end
    TriggerEvent('dpemotes:emote', 'uncuff')
    Citizen.Wait(3000)
    ClearPedTasks(playerPed)
    SetTimecycleModifier("spectator3")
    SetPedMotionBlur(playerPed, true)
    SetPedMovementClipset(playerPed, "move_m@hobo@a", true)
    SetPedIsDrunk(playerPed, true)
    AnimpostfxPlay("FocusOut", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 3.0)
    SetPedArmour(PlayerPedId(), 50)
    TriggerServerEvent("stress:remove", 50000)
    Citizen.Wait(150000)
    SetPedMoveRateOverride(PlayerId(),1.0)
    SetRunSprintMultiplierForPlayer(PlayerId(),1.0)
    SetPedIsDrunk(GetPlayerPed(-1), false)
    SetPedMotionBlur(playerPed, false)
    ResetPedMovementClipset(GetPlayerPed(-1))
    AnimpostfxStopAll()
    ShakeGameplayCam("DRUNK_SHAKE", 0.0)
    SetTimecycleModifierStrength(0.0)
    SetPedArmour(PlayerPedId(), 0)
end)

RegisterNetEvent('drugs:antitox')
AddEventHandler('drugs:antitox', function()
  local playerPed = PlayerPedId()

    RequestAnimSet("move_m@hobo@a")
    while not HasAnimSetLoaded("move_m@hobo@a") do
      Citizen.Wait(0)
    end
    TriggerEvent('dpemotes:emote', 'uncuff')
    Citizen.Wait(3000)
    ClearPedTasks(playerPed)
    SetTimecycleModifier("spectator3")
    SetPedMotionBlur(playerPed, true)
    SetPedMovementClipset(playerPed, "move_m@hobo@a", true)
    SetPedIsDrunk(playerPed, true)
    AnimpostfxPlay("DeathFailMPIn", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 3.0)
    TriggerServerEvent("stress:add", 100000)
    Citizen.Wait(150000)
    SetPedMoveRateOverride(PlayerId(),1.0)
    SetRunSprintMultiplierForPlayer(PlayerId(),1.0)
    SetPedIsDrunk(GetPlayerPed(-1), false)
    SetPedMotionBlur(playerPed, false)
    ResetPedMovementClipset(GetPlayerPed(-1))
    AnimpostfxStopAll()
    ShakeGameplayCam("DRUNK_SHAKE", 0.0)
    SetTimecycleModifierStrength(0.0)
    SetPedArmour(PlayerPedId(), 0)
end)

RegisterNetEvent('drugs:sedative')
AddEventHandler('drugs:sedative', function()
    AnimpostfxPlay("MP_Celeb_Win_Out", 10000001, true)
    Citizen.Wait(10000)
    AnimpostfxStopAll()
end)

RegisterNetEvent('drugs:effect')
AddEventHandler('drugs:effect', function(name)
    for _,k in pairs({"coke","weed", "lsd", "meth", "stimulator", "morphine", "antitox", "sedative"}) do
        if k == name then
            TriggerEvent('drugs:'.. name)
            return
        end
    end
end)
