Config = {}

function _U(a)
	return a
end

Config.Colors = {
			{ index = 0, color = _U('black')},
			{ index = 1, color = _U('graphite')},
			{ index = 2, color = _U('black_metallic')},
			{ index = 3, color = _U('caststeel')},
			{ index = 11, color = _U('black_anth')},
			{ index = 12, color = _U('matteblack')},
			{ index = 15, color = _U('darknight')},
			{ index = 16, color = _U('deepblack')},
			{ index = 21, color = _U('oil')},
			{ index = 147, color = _U('carbon')},
			{ index = 106, color = _U('vanilla')},
			{ index = 107, color = _U('creme')},
			{ index = 111, color = _U('white')},
			{ index = 112, color = _U('polarwhite')},
			{ index = 113, color = _U('beige')},
			{ index = 121, color = _U('mattewhite')},
			{ index = 122, color = _U('snow')},
			{ index = 131, color = _U('cotton')},
			{ index = 132, color = _U('alabaster')},
			{ index = 134, color = _U('purewhite')},
			{ index = 4, color = _U('silver')},
			{ index = 5, color = _U('metallicgrey')},
			{ index = 6, color = _U('laminatedsteel')},
			{ index = 7, color = _U('darkgray')},
			{ index = 8, color = _U('rockygray')},
			{ index = 9, color = _U('graynight')},
			{ index = 10, color = _U('aluminum')},
			{ index = 13, color = _U('graymat')},
			{ index = 14, color = _U('lightgrey')},
			{ index = 17, color = _U('asphaltgray')},
			{ index = 18, color = _U('grayconcrete')},
			{ index = 19, color = _U('darksilver')},
			{ index = 20, color = _U('magnesite')},
			{ index = 22, color = _U('nickel')},
			{ index = 23, color = _U('zinc')},
			{ index = 24, color = _U('dolomite')},
			{ index = 25, color = _U('bluesilver')},
			{ index = 26, color = _U('titanium')},
			{ index = 66, color = _U('steelblue')},
			{ index = 93, color = _U('champagne')},
			{ index = 144, color = _U('grayhunter')},
			{ index = 156, color = _U('grey')},
			{ index = 27, color = _U('red')},
			{ index = 28, color = _U('torino_red')},
			{ index = 29, color = _U('poppy')},
			{ index = 30, color = _U('copper_red')},
			{ index = 31, color = _U('cardinal')},
			{ index = 32, color = _U('brick')},
			{ index = 33, color = _U('garnet')},
			{ index = 34, color = _U('cabernet')},
			{ index = 35, color = _U('candy')},
			{ index = 39, color = _U('matte_red')},
			{ index = 40, color = _U('dark_red')},
			{ index = 43, color = _U('red_pulp')},
			{ index = 44, color = _U('bril_red')},
			{ index = 46, color = _U('pale_red')},
			{ index = 143, color = _U('wine_red')},
			{ index = 150, color = _U('volcano')},
			{ index = 135, color = _U('electricpink')},
			{ index = 136, color = _U('salmon')},
			{ index = 137, color = _U('sugarplum')},
			{ index = 54, color = _U('topaz')},
			{ index = 60, color = _U('light_blue')},
			{ index = 61, color = _U('galaxy_blue')},
			{ index = 62, color = _U('dark_blue')},
			{ index = 63, color = _U('azure')},
			{ index = 64, color = _U('navy_blue')},
			{ index = 65, color = _U('lapis')},
			{ index = 67, color = _U('blue_diamond')},
			{ index = 68, color = _U('surfer')},
			{ index = 69, color = _U('pastel_blue')},
			{ index = 70, color = _U('celeste_blue')},
			{ index = 73, color = _U('rally_blue')},
			{ index = 74, color = _U('blue_paradise')},
			{ index = 75, color = _U('blue_night')},
			{ index = 77, color = _U('cyan_blue')},
			{ index = 78, color = _U('cobalt')},
			{ index = 79, color = _U('electric_blue')},
			{ index = 80, color = _U('horizon_blue')},
			{ index = 82, color = _U('metallic_blue')},
			{ index = 83, color = _U('aquamarine')},
			{ index = 84, color = _U('blue_agathe')},
			{ index = 85, color = _U('zirconium')},
			{ index = 86, color = _U('spinel')},
			{ index = 87, color = _U('tourmaline')},
			{ index = 127, color = _U('paradise')},
			{ index = 140, color = _U('bubble_gum')},
			{ index = 141, color = _U('midnight_blue')},
			{ index = 146, color = _U('forbidden_blue')},
			{ index = 157, color = _U('glacier_blue')},
			{ index = 42, color = _U('yellow')},
			{ index = 88, color = _U('wheat')},
			{ index = 89, color = _U('raceyellow')},
			{ index = 91, color = _U('paleyellow')},
			{ index = 126, color = _U('lightyellow')},
			{ index = 49, color = _U('met_dark_green')},
			{ index = 50, color = _U('rally_green')},
			{ index = 51, color = _U('pine_green')},
			{ index = 52, color = _U('olive')},
			{ index = 53, color = _U('light_green')},
			{ index = 55, color = _U('lime_green')},
			{ index = 56, color = _U('forest_green')},
			{ index = 57, color = _U('lawn_green')},
			{ index = 58, color = _U('imperial_green')},
			{ index = 59, color = _U('green_bottle')},
			{ index = 92, color = _U('citrus_green')},
			{ index = 125, color = _U('green_anis')},
			{ index = 128, color = _U('khaki')},
			{ index = 133, color = _U('army_green')},
			{ index = 151, color = _U('dark_green')},
			{ index = 152, color = _U('hunter_green')},
			{ index = 155, color = _U('matte_foilage_green')},
			{ index = 36, color = _U('tangerine')},
			{ index = 38, color = _U('orange')},
			{ index = 41, color = _U('matteorange')},
			{ index = 123, color = _U('lightorange')},
			{ index = 124, color = _U('peach')},
			{ index = 130, color = _U('pumpkin')},
			{ index = 138, color = _U('orangelambo')},
			{ index = 45, color = _U('copper')},
			{ index = 47, color = _U('lightbrown')},
			{ index = 48, color = _U('darkbrown')},
			{ index = 90, color = _U('bronze')},
			{ index = 94, color = _U('brownmetallic')},
			{ index = 95, color = _U('Expresso')},
			{ index = 96, color = _U('chocolate')},
			{ index = 97, color = _U('terracotta')},
			{ index = 98, color = _U('marble')},
			{ index = 99, color = _U('sand')},
			{ index = 100, color = _U('sepia')},
			{ index = 101, color = _U('bison')},
			{ index = 102, color = _U('palm')},
			{ index = 103, color = _U('caramel')},
			{ index = 104, color = _U('rust')},
			{ index = 105, color = _U('chestnut')},
			{ index = 108, color = _U('brown')},
			{ index = 109, color = _U('hazelnut')},
			{ index = 110, color = _U('shell')},
			{ index = 114, color = _U('mahogany')},
			{ index = 115, color = _U('cauldron')},
			{ index = 116, color = _U('blond')},
			{ index = 129, color = _U('gravel')},
			{ index = 153, color = _U('darkearth')},
			{ index = 154, color = _U('desert')},
			{ index = 71, color = _U('indigo')},
			{ index = 72, color = _U('deeppurple')},
			{ index = 76, color = _U('darkviolet')},
			{ index = 81, color = _U('amethyst')},
			{ index = 142, color = _U('mysticalviolet')},
			{ index = 145, color = _U('purplemetallic')},
			{ index = 148, color = _U('matteviolet')},
			{ index = 149, color = _U('mattedeeppurple')},
			{ index = 117, color = _U('brushedchrome')},
			{ index = 118, color = _U('blackchrome')},
			{ index = 119, color = _U('brushedaluminum')},
			{ index = 120, color = _U('chrome')},
			{ index = 37, color = _U('gold')},
			{ index = 158, color = _U('puregold')},
			{ index = 159, color = _U('brushedgold')},
			{ index = 160, color = _U('lightgold')}
}

Config.CarShops = {
--[[
	[1] = {
		id = 1,
		pos = vector3(-42.96, -1098.16, 26.42),
		heading = 0.0,
		label = "Автосалон",
		items = {
			{ name = 't20', label = 'T20', price = 100 },
			{ name = 'lp770cop', label = 'LP 770 Cop', price = 100 },
			{ name = 'blista', label = 'Blista', price = 100 },
			{ name = 'panto', label = 'Panto', price = 100 },
		}
	},

	[2] = {
		id = 2,
		pos = vector3(1270.44, -3298.82, 5.9),
		heading = 0.0,
		label = "Поставки",
		items = {
			{name = 't20', label = 'Остов T20', price = 100, frame = true}
		}
	},
]]
	[1] = {
		id = 1,
		carPos = vector3(-786.54, -243.12, 36.46),
		pos = vector3(-786.74, -237.51, 37.25),
		heading = 320.0,
		label = "Автосалон 2",
		categories = {
			['supercars'] = {
				name = 'Суперкары',
				icon = 'car_super',
				items = {
						{
							name = 't20',
							label = 'T20',
							price = 120,
							colors = Config.Colors,
						},
						{
							name = 'lp770cop',
							label = 'LP 770 Cop',
							price = 120,
							colors = Config.Colors,
						},
				}
			},

			['sport'] = {
				name = 'Спорт',
				icon = 'car_sport',
				items = {
					{ name = 'blista', label = 'Blista', price = 100 },
					{ name = 'panto', label = 'Panto', price = 100 },
				}
			},

		}
	}
}
