-- SilentSiren
SILENTSIREN_PNAME = "_IS_SIREN_SILENT"
SILENTSIREN_HOTKEY = 58 -- G
SILENTHOTKEY_MAXTIMEOUT = 15

-- BlipSiren
BLIPSIREN_PNAME = "_IS_SIREN_BLIP"

-- SirenSound
SIRENSOUND_PNAME = "_IS_SIREN_ALT_SOUND"
SIRENSOUND_HOTKEY = 21 -- LEFT SHIFT